/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp /usr/share/dbus-1/interfaces/org.freedesktop.DeviceKit.Disks.xml -m -p OrgFreedesktopDeviceKitDisks
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "OrgFreedesktopDeviceKitDisks.h"

/*
 * Implementation of interface class OrgFreedesktopDeviceKitDisksInterface
 */

OrgFreedesktopDeviceKitDisksInterface::OrgFreedesktopDeviceKitDisksInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDeviceKitDisksInterface::~OrgFreedesktopDeviceKitDisksInterface()
{
}


#include "OrgFreedesktopDeviceKitDisks.moc"
